apiVersion: apps/v1
kind: Deployment
metadata:
  name: financer-api-deployment
  annotations:
    kubernetes.io/change-cause: "Initial"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financer-api
  template:
    metadata:
      name: financerapi
      labels:
        env: prod
        app: financer-api
        app.kubernetes.io/name: financer-api
    spec:
      containers:
        - name: financer-api
          image: yuri1999/financeapi:v4
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: Mongo__DbConnectionString
              valueFrom:
                secretKeyRef:
                  name: financer-api-secrets
                  key: Mongo__DbConnectionString
            - name: Mongo__DatabaseName
              valueFrom:
                configMapKeyRef:
                  name: financer-api-config
                  key: Mongo__DatabaseName
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
