apiVersion: v1
kind: Service
metadata:
  name: financer-api-service
spec:
  selector:
    # app.kubernetes.io/name: financer-api
    app: financer-api
  ports:
  - name: financer-api-port
    protocol: TCP
    port: 8080
    targetPort: 80
    # nodePort: 30080
  type: LoadBalancer