apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  labels:
    app: mongodb
data:
  MONGO_INITDB_DATABASE: FinancerJob
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: rootpassword
